### ISSUE TITLE
Escape problem in tpl/Reservation/pdf.tpl

### ISSUE THREAD

**Issue by wtfred** [effgarces/BookedScheduler#12]
Hello there,

First of all, a big thanks for this repository! It's relly usefull since the sourceforge is gone...

We updated our booked with release 2.8.5.2, and found an issue with french language.

In `tpl/Reservation/pdf.tpl`, line 90, there is `[{ content: '{translate key=RepeatUntilPrompt}', styles: { fontStyle: 'bold'}},`

Problem is, in french the "RepeatUntilPrompt" label is "Jusqu\'au", so we ended up with a syntax error.

I fixed it by replacing the line with: `[{ content: '{{translate key='RepeatUntilPrompt'}|escape('javascript')', styles: { fontStyle: 'bold'}},`

If you need i could make a PR, right now i don't have the time but let me know!

**Comment by effgarces** [comment]
I just added the fix to the bugfix branch, thanks for the information.

**Comment by wtfred** [comment]
Hello again, i'm really sorry but turns out my fix was worst than the original error, i must have messed up with copy/paste because yesterday i thought i had something working...

Anyway, i don't know how to use correctly the `|escape('javascript')`, so i just replaced single with doubles quotes.
`[{ content: "{translate key='RepeatUntilPrompt'}", styles: { fontStyle: 'bold'}},`

**Comment by effgarces** [comment]
These things happen, I've fixed the issue with the escape (`[{ content: '{translate key=RepeatUntilPrompt|escape:'javascript'}', styles: { fontStyle: 'bold'}},`) and after checking the rest of the file I've added this fix to two more places, so thank you for letting me know and following up.

**Comment by wtfred** [comment]
Hello,
The fix in 2.8.5.3 doesn't seems to work. With french label "Jusqu'au", it still make recurrent reservation impossible to edit because of "SyntaxError"
Looks like the escape filter is not applied correctly, so i still had to quote it with double quotes instead of single to make it work...

**Comment by effgarces** [comment]
That is weird, I swear I tested it and it was working, must have missed something, I will check it as soon as I can.

**Comment by effgarces** [comment]
I just pushed a final (I hope) fix. The previous the "fix" as missing a couple of brackets, I think that while testing I must have forgotten to clear the cache and missed that it wasn't working.
I've tested it and seems to working properly now, I also updated the latest maintenance release with the correction.
