### ISSUE TITLE
Duration vs 

### ISSUE THREAD

**Issue by michel-thomas** [effgarces/BookedScheduler#122]
Hello,

is it possible to have a different default duration than the ability to create other slot duration for reservations ?

I notice that when defining 1 hour slot duration in planning configuration, I can't create a reservation that longs 1h30, 0h45, etc

Maybe I missed something?

Thanks for your help.

Thomas

**Comment by treborin** [comment]
Hi @michel-thomas ,
For reservations that longs 1h30, 0h45, just define 15 min slots and that's all

**Comment by michel-thomas** [comment]
Thanks @treborin but If I do so, my default duration will be 15 min.

I wanted to know if it is possible to define 1 hour default duration and adjust with 15 min steps?

Thanks

**Comment by treborin** [comment]
@michel-thomas , when you create a schedule, you must give it a times slots layout. And then, when you create a resource, you can assign it any schedule you want (let's say with a 15 min slots layout, in your case) and a specific "duration" : Resevations must last at least 0 days 1 hours 0 min (You must to uncheck the first option in the form "There is no minimum reservation duration")
This way, ou have 15 min slots and an automatic minimum of 1 hour duration by default.

So easy :)
Hope this help you

**Comment by michel-thomas** [comment]
Thanks for your help. This is more clear for me now.
