### ISSUE TITLE
Week sarting on monday (on datepicker)

### ISSUE THREAD

**Issue by treborin** [effgarces/BookedScheduler#20]
Hi,
Anyone knows if there is a way to see datepicker calendars (the fantastic one on top of view-shedule.php page, and also on any datepicker form field) satrting from monday instead of sunday (we use that format in Spain)?
I can`t find the right way to render that small calendar with the weeks starting from monday. It´d be something easy to do.
And the same is with the big calendar on view-calendar.php page.
It'd be great to have this option available inside config.php. This way, you can configure as per your needs.

Hope anyone can help with this

**Comment by treborin** [comment]
**UPDATE**:
I hve found this:
File Controls/DatePickerSetupControl.php, If you change on line 49 the value of 'FirstDay' to 1 (it's set to 0 by default), then you get datepickers form fields starting from monday: 
`$this->SetDefault('FirstDay', 1);`

But view-shedule.php and view-calendar.php do not start on monday with this mod. So these files get var FisrtDay from another place. Let´s continue searching... :)

**Comment by fsi2000** [comment]
Hi, have you checked Application Management->Schedules. There you can set the first day of the week. Click on "Sunday" and change it.

**Comment by treborin** [comment]
@fsi2000 Done! You are right. I missed that. Too many options 👍

**Comment by aliciarf2611** [comment]
Hi, for view-shedule.php and view-calendar.php i just modify tpl/Calendar/Calendar-page-base.tpl substituing firstDay: {$FirstDay} by firstDay: 1. (Don't forget to flush cached files later)

**Comment by treborin** [comment]
Thanks @aliciarf2611, that mod solves the view-calendar.php 👍.
Regarding view-shedule.php, if you set it in shedules configuration to starts on "Today" (as i need), the 3 small datepicker calendars on top steel shows sunday as the first day of the week.

**Comment by aliciarf2611** [comment]
I also have the schedules on 'today' and I see the calendars of the schedule.php inside the datepicker starting on Monday. sorry, I have inherited a code with changes and maybe we don't have the same version.

**Comment by treborin** [comment]
thanks @aliciarf2611. I use 2.8.5
I've made some modifications for my needs, but the base code is 2.8.5
There must be a way to solve it and i continue searching inside app code. Once i have it, i'!! report here
