### ISSUE TITLE
gitter chat

### ISSUE THREAD

**Issue by apfelchips** [effgarces/BookedScheduler#21]
Hey I've set up a Gitter.im Chatroom so we mustn't talk about small tweaks  / strategy / whatever on GitHub Issues and pull requests.
I'd of course give @effgarces admin access to the room.
Would be awesome If you'd add it to the Readme.md 

Also have a look at my fork for additional documentation in /doc.

[![Gitter](https://badges.gitter.im/bookedscheduler/community.svg)](https://gitter.im/bookedscheduler/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

https://gitter.im/bookedscheduler

**Comment by effgarces** [comment]
Hi thanks for the initiative, I'm not sure if we have enough interested people to fill a chat room, but I can certainly add it to the Readme.md and help spread the info. dad5dc245
