### ISSUE TITLE
Link on error.tpl does not work properly

### ISSUE THREAD

**Issue by treborin** [effgarces/BookedScheduler#35]
Hi there,

I've found this on error.tpl:
If you are not loged in, and you try to click the link and view any resource on view-schedule.php grid, then that link goes to an error page, telling that you can't access, and the link below tells you (in english): "Return to the last page that you were on". But this link do not works propertly.
I've found this solution:
Substitute this line insde error.tpl: 
`<h5><a href="//{$smarty.server.HTTP_HOST}{$smarty.server.REQUEST_URI}">{translate key='ReturnToPreviousPage'}</a>/h5>`
By this:
`<h5><a href="#" onclick="goBack()">{translate key='ReturnToPreviousPage'}</a></h5>`

And you need to include this JavaScript code outside the div and before the foot, like this:

```
</div>

<script>
function goBack() {
 window.history.back();
}
</script>

{include file="javascript-includes.tpl"}
{include file='globalfooter.tpl'}
```

It works ok for me, tested on Firefox, Chrome and Edge browsers.
Hope it helps :)

**Comment by effgarces** [comment]
Thanks for the report/solution, I will try to check this as soon as possible.

**Comment by blazindrop** [comment]
Why not just submit a PR @treborin  since you already have a fix :)

**Comment by effgarces** [comment]
Sorry about this one, it slipped between multiple emails/notifications/etc. So thanks for the PR, and the message to alert me that this had slipped my mind.

**Comment by treborin** [comment]
No problem @effgarces . Happy to help :)
Good proposal @blazindrop. Thanks
