### ISSUE TITLE
Can't find /tpl_c in the repo

### ISSUE THREAD

**Issue by raghuchahar007** [effgarces/BookedScheduler#39]
There is a step mentioned in the readme of booked schedular installation, where user has to change permission of /tpl_c, /tpl and /uploads folder. But I cant find out /tpl_c folder in this repo, please help me out.
<img width="1440" alt="Screen Shot 2021-04-29 at 7 32 02 PM" src="https://user-images.githubusercontent.com/39947360/116563734-ebcc9400-a921-11eb-86a9-8c090c2c18fe.png">

**Comment by treborin** [comment]
You are right. Just create it at the same level of /tpl and will works fine

**Comment by apfelchips** [comment]
actually It should create it automatically on first page load. I'll update the documentation to only troubleshoot permissions when it isn't created.

**Comment by raghuchahar007** [comment]
> You are right. Just create it at the same level of /tpl and will works fine

Thanks @treborin, It is working now
