### ISSUE TITLE
Apostrophe in name prevents booking

### ISSUE THREAD

**Issue by ehk20** [effgarces/BookedScheduler#44]
This seems to be recent regression. In v2.8.5.3 (from here), user Aaron O'Sullivan is unable to create a booking as the "Create" button never accepts a click. Removing the ' from the Last Name resolves (ie. for Aaron OSullivan). Doesn't seem to be an issue in 2.8.5 (plain) we have running somewhere else.

**Comment by effgarces** [comment]
Thanks for bringing attention to this, I've just added a commit to develop branch, that should solve it.
