### ISSUE TITLE
Removing copyright and license

### ISSUE THREAD

**Issue by blazindrop** [effgarces/BookedScheduler#52]
First I think it's great this repository exists to ensure the source code is available to all those who want to use and modify it. Seeing the recent changes that remove the copyright and open source license, however, make me now question the viability of this project and those wishing to "fork" and modify the work for their purpose.

In https://softwareengineering.stackexchange.com/questions/148146/open-source-code-with-no-license-can-i-fork-it , while not legal guidance, suggests a project without any license implies no permissions to modify, use or redistribute the work. In https://opensource.guide/legal/ it says:

> Making your GitHub project public is not the same as licensing your project. Public projects are covered by GitHub’s Terms of Service, which allows others to view and fork your project, but your work otherwise comes with no permissions.
> If you want others to use, distribute, modify, or contribute back to your project, you need to include an open source license. For example, someone cannot legally use any part of your GitHub project in their code, even if it’s public, unless you explicitly give them the right to do so.

With no license nobody technically has any rights to use, distribute or modify. Does Nick Korbel technically retain the copyright since he authored the original source code?  Was there a discussion around removing the license and copyright?

**Comment by treborin** [comment]
@apfelchips, absolutely agree 👍.
We all thanks to Nick Korbel for the hard job in the past, but there is a very hard job in the near future too and sooner or later this will be a new different and modern GPL project.

**Comment by blazindrop** [comment]
Awesome thanks for explaining I saw there was a LICENSE file now in the root directory also. Just brought this up because I want to see this keep succeeding :)
