### ISSUE TITLE
Create Reservation not possible

### ISSUE THREAD

**Issue by Steffeng5** [effgarces/BookedScheduler#54]
After updating from 2.7.* to 2.8.5.3 it is not possible to create reservations anymore.
WebInspector shows a parsing error:
<img width="331" alt="Bildschirmfoto 2021-06-04 um 10 09 47" src="https://user-images.githubusercontent.com/822659/120769230-30e57680-c51d-11eb-9e09-81feb77fc169.png">

reservation.php is rendered with a warning of a pdf library:
<img width="1064" alt="Bildschirmfoto 2021-06-04 um 10 12 10" src="https://user-images.githubusercontent.com/822659/120769602-976a9480-c51d-11eb-8084-b51fce6594f1.png">

this results in bad html where it is not possible to click the "Create" Button to create the reservation

**Comment by Steffeng5** [comment]
This can be hotfixed by changing tpl/reservation/pdf.tpl with:

**Comment by Steffeng5** [comment]
This is a duplicate of #40 : Can you create a 2.8.5.4 with this PR?

**Comment by effgarces** [comment]
Could you check if the same problem occurs using the current pdf.tpl in the develop branch?

**Comment by Steffeng5** [comment]
See above :) It is a duplicate of #40
