### ISSUE TITLE
Ordering customers do not works when click on head fields

### ISSUE THREAD

**Issue by treborin** [effgarces/BookedScheduler#55]
Hi,
On manage_users.php, when you list customers and need to order them using head fields, it works the fist time you click on any head field, but if you then try to click on any head field again to reorder, then it does not work and returns an 403 server error.

**Comment by marcodidom** [comment]
Hi,
I haven't this problem in my installation

Marco

**Comment by treborin** [comment]
Thanks @marcodidom. Wich version do you have installed?

**Comment by marcodidom** [comment]
last 2.8.5.3
