### ISSUE TITLE
Apostrophe in the username breaks the reservation page.

### ISSUE THREAD

**Issue by Seaborg** [effgarces/BookedScheduler#68]
Booked Scheduler v2.8.5.3

Username with extra apostrophe breaks the reservation page.

i.e. "D'Blah"

Code breaks here:
./tpl/Reservation/pdf.tpl

violating variable:
{ user: '{$ReservationUserName}'}

Which makes it impossible to load extra attributes thus make the booking.

**Comment by effgarces** [comment]
This  was already fixed on the dev version and as of a couple minutes ago is also in the latest maintenance release, 2.8.5.4

**Comment by Seaborg** [comment]
Thank you. Much appreciated.
