### ISSUE TITLE
In WebServices (API REST)  Update a resource removes the images

### ISSUE THREAD

**Issue by FelipeSanchezCalzada** [effgarces/BookedScheduler#83]
I have checked it in version 2.8.5.3.

I create a Resource from the web and when I update it from the services, all the images of the resource are deleted.

**Comment by treborin** [comment]
Hi @FelipeSanchezCalzada ,
Have you tried to empty tmp_c dir?

**Comment by FelipeSanchezCalzada** [comment]
@treborin 
Thanks for answering, I don't know what you mean by "empty tmp_c dir".

**Comment by treborin** [comment]
Sorry @FelipeSanchezCalzada, the rigth name for that dir is tpl_c.
Try to delete everything inside it. It's located here: yourdomai.com/yourdir/tpl_c and it contains lots of catched files.
Btw: dir = folder :)

**Comment by FelipeSanchezCalzada** [comment]
It makes no difference if I remove the contents of "tpl_c ".

The steps to follow to reproduce the error are:
1. Add a resource normally from the web
2. Add some images to the resource
3. From the URL "Web/Services/index.php/Resources/:id" (REST Services) update the resource, changing for instance the resource name.
4. The resource has lost all images after the update.

It seems to be a problem in the REST services code.

**Comment by effgarces** [comment]
Thanks for steps to reproduce the issue, I've marked as bug and added to the list of things check/fix
