### ISSUE TITLE
Test Number & Test String

### ISSUE THREAD

**Issue by PonlorkBeang** [effgarces/BookedScheduler#91]
From v2.8.5 i found Test Number & Test String are keeping in "New Reservation". It should be remove from production.
![image](https://user-images.githubusercontent.com/97224078/149265606-6b34a6b8-38a3-440c-ad4e-760d01fb5642.png)

**Comment by effgarces** [comment]
Those custom attributes are only added if during the installation the demo data is installed. They are meant as an example of what you can do with Booked.

**Comment by IMDEA-Matteosch** [comment]
@effgarces Hey !

I wanted to ask here instead of creating a ticket, but not sure this is the way. Is there a way to remove that afterwards ? I don't find those attributes nowhere.

Thanks a lot!
